my_string = str (input('Какое сейчас время суток: '))
print('Добрый', my_string)
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', '_'))
print(my_string [0])
print(my_string [-1])